services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: user_redis
    ports:
      - ${REDIS_EXTERNAL_PORT}:6379
    networks:
      - user-service-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - ${APP_EXTERNAL_PORT}:8080
    environment:
      - SPRING_DATASOURCE_URL=${DOCKER_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DOCKER_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DOCKER_DATASOURCE_PASSWORD}
    restart: no
    depends_on:
      - user-postgresql
    networks:
      - user-service-network

  user-postgresql:
    image: postgres:${POSTGRES_VERSION}
    container_name: user_postgres
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      PGPASSWORD: ${PGPASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -U postgres_user -d users"
      interval: 2s
      timeout: 20s
      start_period: 10s
      retries: 10
    networks:
      - user-service-network

volumes:
  postgresql_data:

networks:
  user-service-network:
    driver: bridge


