-- Основная таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(64) UNIQUE NOT NULL,
    name        VARCHAR(64) NOT NULL,
    surname     VARCHAR(64) NOT NULL,
    email       VARCHAR(64) UNIQUE NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT current_timestamp,
    updated_at  TIMESTAMPTZ DEFAULT current_timestamp
);